/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Theme-based colors using CSS variables
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-light': 'var(--primary-light)',
        background: 'var(--background)',
        'background-secondary': 'var(--background-secondary)',
        'background-tertiary': 'var(--background-tertiary)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        border: 'var(--border)',
        'border-hover': 'var(--border-hover)',
        accent: 'var(--accent)',
        highlight: 'var(--highlight)',
        success: 'var(--success)',
        error: 'var(--error)',
        warning: 'var(--warning)',
        info: 'var(--info)',
        // Animated background colors
        'hero-bg': 'var(--hero-background)',
        'hero-gradient-start': 'var(--hero-gradient-start)',
        'hero-gradient-mid': 'var(--hero-gradient-mid)',
        'hero-gradient-end': 'var(--hero-gradient-end)',
        'hero-grid': 'var(--hero-grid-color)',
        'hero-pattern': 'var(--hero-pattern-stroke)',
        'hero-pattern-alt': 'var(--hero-pattern-stroke-alt)',
        'hero-dot': 'var(--hero-dot-color)',
        'hero-overlay-start': 'var(--hero-overlay-start)',
        'hero-overlay-mid': 'var(--hero-overlay-mid)',
        'hero-overlay-end': 'var(--hero-overlay-end)',
        'projects-gradient-start': 'var(--projects-gradient-start)',
        'projects-gradient-mid': 'var(--projects-gradient-mid)',
        'projects-gradient-end': 'var(--projects-gradient-end)',
        'projects-orb-primary': 'var(--projects-orb-primary)',
        'projects-orb-secondary': 'var(--projects-orb-secondary)',
        'projects-pattern': 'var(--projects-pattern-stroke)',
        'projects-float': 'var(--projects-float-color)',
        'projects-float-alt': 'var(--projects-float-color-alt)',
        'skills-gradient-start': 'var(--skills-gradient-start)',
        'skills-gradient-mid': 'var(--skills-gradient-mid)',
        'skills-gradient-end': 'var(--skills-gradient-end)',
        'skills-orb-primary': 'var(--skills-orb-primary)',
        'skills-orb-secondary': 'var(--skills-orb-secondary)',
        'skills-pattern': 'var(--skills-pattern-stroke)',
        'skills-float': 'var(--skills-float-color)',
        'skills-float-alt': 'var(--skills-float-color-alt)',
        'skills-gear': 'var(--skills-gear-color)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
}